# --- Local DB (Docker Compose) ---
spring:
  datasource:
    # 환경 변수(SPRING_DATASOURCE_URL)가 없으면 우측의 기본값 사용
    url: jdbc:postgresql://db:5432/imagepost_db
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: postgres
    driver-class-name: org.postgresql.Driver

  cloud:
    aws:
      s3:
        enabled: false

# --- Local File Storage ---
file:
  # 환경 변수(FILE_UPLOAD_DIR)가 없으면 우측의 기본값 사용
  upload-dir: ${FILE_UPLOAD_DIR:./uploads/}